#ifndef H_ANSICOLORS
#define H_ANSICOLORS

#define ANSI_RED 31
#define ANSI_BG_RED 41

#define ANSI_RESET_ALL "\x1B[0m"

#define ANSI_COLOR_ID_BLK 0
#define ANSI_COLOR_ID_RED 1
#define ANSI_COLOR_ID_GRN 2
#define ANSI_COLOR_ID_YEL 3
#define ANSI_COLOR_ID_BLU 4
#define ANSI_COLOR_ID_MAG 5
#define ANSI_COLOR_ID_CYN 6
#define ANSI_COLOR_ID_WHT 7
#define ANSI_COLOR_ID_FADED_BLK 8
#define ANSI_COLOR_ID_FADED_RED 9
#define ANSI_COLOR_ID_FADED_GRN 10
#define ANSI_COLOR_ID_FADED_YEL 11
#define ANSI_COLOR_ID_FADED_BLU 12
#define ANSI_COLOR_ID_FADED_MAG 13
#define ANSI_COLOR_ID_FADED_CYN 14
#define ANSI_COLOR_ID_FADED_WHT 15

#define ANSI_COLOR_ID_LIGHT_BLK 235
#define ANSI_COLOR_ID_LIGHTER_BLK 238
#define ANSI_COLOR_ID_DARK_BLK 0

#define ANSI_COLOR_ID_BRIGHT_WHT 15
#define ANSI_COLOR_ID_DARK_WHT 250
#define ANSI_COLOR_ID_DARKER_WHT 245




#endif